version: 2

models:

  - name: stg_orders
    description: "Orders cleaned and typed from bronze"
    columns:
      - name: order_id
        description: "Unique identifier for order (PK)"
        tests:
          - unique
          - not_null
      - name: customer_id
        description: "Customer that make the order"
        tests:
          - not_null
      - name: order_status
        description: "Status of the order (delivered, shipped, canceled, etc.)"

  - name: stg_customers
    description: "Customers cleaned and typed from bronze"
    tests:
      - dbt_utils.expression_is_true:
          expression: "length(customer_zip_code_prefix) = 5"
    columns:
      - name: customer_id
        description: "Unique identifier for each customer (PK)"
        tests:
          - unique
          - not_null
      - name: customer_unique_id
        description: "Identifier for each customer (in their multiple orders)"
        tests:
          - not_null
      - name: customer_zip_code_prefix
        description: "First five digits of the zip code"
        tests:
          - not_null
      - name: customer_state
        description: "27 states of Brazil"
        tests:
          - accepted_values:
              values: ['AC','AL','AM','AP','BA','CE','DF','ES','GO','MA','MG','MS','MT','PA','PB','PE','PI','PR','RJ','RN','RO','RR','RS','SC','SE','SP','TO']
  
  - name: stg_geolocation
    description: "Geospatial data of the cities"
    tests:
      - dbt_utils.expression_is_true:
          expression: "length(geolocation_zip_code_prefix) = 5"
    columns: 
    - name: geolocation_zip_code_prefix
      description: "First five digits of the zip code"
      tests:
        - not_null
    - name: geolocation_state
      description: "27 states of Brazil"
      tests:
        - accepted_values:
            values: ['AC','AL','AM','AP','BA','CE','DF','ES','GO','MA','MG','MS','MT','PA','PB','PE','PI','PR','RJ','RN','RO','RR','RS','SC','SE','SP','TO']
  
  - name: stg_sellers
    description: "Seller data"
    tests:
      - dbt_utils.expression_is_true:
          expression: "length(seller_zip_code_prefix) = 5"
    columns:
      - name: seller_id
        description: "Unique identifier for each seller (PK)"
        tests:
          - unique
          - not_null
      - name: seller_zip_code_prefix
        description: "First five digits of the zip code of the seller"
        tests:
          - not_null
      - name: seller_state
        description: "27 states of Brazil"
        tests:
          - accepted_values:
              values: ['AC','AL','AM','AP','BA','CE','DF','ES','GO','MA','MG','MS','MT','PA','PB','PE','PI','PR','RJ','RN','RO','RR','RS','SC','SE','SP','TO']
  
  - name: stg_order_items
    description: "The items that contains each order"
    columns:
      - name: order_id
        description: "Unique identifier for each order (FK)"
        tests:
        - not_null
      - name: order_item_id
        description: "Identifier for each product inside an order (FK)"
        tests:
          - not_null
      - name: product_id
        description: "Identifier for each product (FK)"
        tests:
          - not_null
      - name: seller_id
        description: "Identifier for each seller (FK)"
        tests:
          - not_null

  - name: stg_order_payments
    description: "Payments of the orders"
    columns:
      - name: order_id
        description: "Unique identifier for each order (FK)"
        tests:
          - not_null
      - name: payment_type
        description: "How payed the order"
        tests:
          - accepted_values:
              values: ['credit_card','boleto','voucher','debit_card','not_defined']
        
        