version: 2

models:

  - name: stg_orders
    description: "Orders cleaned and typed from bronze"
    columns:
      - name: order_id
        description: "Unique identifier for order (PK)"
        tests:
          - unique
          - not_null
      - name: customer_id
        description: "Customer that make the order"
        tests:
          - not_null
      - name: order_status
        description: "Status of the order (delivered, shipped, canceled, etc.)"

  - name: stg_customers
    description: "Customers cleaned and typed from bronze"
    tests:
      - dbt_utils.expression_is_true:
          expression: "length(customer_zip_code_prefix) = 5"
    columns:
      - name: customer_id
        description: "Unique identifier for each customer (PK)"
        tests:
          - unique
          - not_null
      - name: customer_unique_id
        description: "Identifier for each customer (in their multiple orders)"
        tests:
          - not_null
      - name: customer_zip_code_prefix
        description: "First five digits of the zip code"
      - name: customer_state
        description: "27 states of Brazil"
        tests:
          - accepted_values:
              values: ['AC','AL','AM','AP','BA','CE','DF','ES','GO','MA','MG','MS','MT','PA','PB','PE','PI','PR','RJ','RN','RO','RR','RS','SC','SE','SP','TO']
  
  - name: stg_geolocation
    description: "Geospatial data of the cities"
    tests:
      - dbt_utils.expression_is_true:
          expression: "length(geolocation_zip_code_prefix) = 5"
    columns: 
    - name: geolocation_zip_code_prefix
      description: "First five digits of the zip code"
    - name: geolocation_state
      description: "27 states of Brazil"
      tests:
        - accepted_values:
            values: ['AC','AL','AM','AP','BA','CE','DF','ES','GO','MA','MG','MS','MT','PA','PB','PE','PI','PR','RJ','RN','RO','RR','RS','SC','SE','SP','TO']
        
        